name: 🔒 Security Vulnerability Report
description: Report a security vulnerability in ANUS
title: '[SECURITY] '
labels: ['security', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ Important Security Guidelines

        **DO NOT** include direct exploits or step-by-step attack guides in this public issue.
        Describe the vulnerability's impact, but keep implementation details private.

        A maintainer will contact you if more details are needed for a private discussion.

  - type: dropdown
    id: vulnerability-type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Code injection
        - Path traversal
        - Privilege escalation
        - Information disclosure
        - Denial of service
        - Authentication/authorization bypass
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Estimated Severity
      description: How severe do you think this vulnerability is?
      options:
        - Critical (Complete system compromise)
        - High (Significant impact)
        - Medium (Moderate impact)
        - Low (Minor impact)
        - Informational
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact Description
      description: Describe what an attacker could accomplish with this vulnerability
      placeholder: 'An attacker could... This would allow... The impact includes...'
    validations:
      required: true

  - type: textarea
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions of ANUS are affected?
      placeholder: 'v0.0.2, latest main branch, etc.'
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: OS, Node.js version, installation method, etc.
      placeholder: |
        OS: macOS 14.0
        Node.js: v20.0.0
        ANUS version: v0.0.2
        Installation: npm install -g @anus-dev/anus

  - type: textarea
    id: discovery-method
    attributes:
      label: Discovery Method
      description: How did you discover this vulnerability? (optional)
      placeholder: 'Code review, testing, automated scanning, etc.'

  - type: checkboxes
    id: scope-confirmation
    attributes:
      label: Scope Confirmation
      description: Please confirm this vulnerability is in scope
      options:
        - label: This vulnerability is in the ANUS tool itself (not the underlying AI model behavior)
          required: true
        - label: I have not included direct exploit code or step-by-step attack guides
          required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information
